spring:
  mvc:
    enforced-prefixes:
      - /actuator
      - /doc
      - /rest
      - /favicon.ico


management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      path-mapping.health: status
    enabled-by-default: false

  server:
    add-application-context-header: true

server:
  port: 12000
